### ISSUE TITLE
Remove configuration logging at startup

### ISSUE THREAD

**Issue by dylanmei** [Nordstrom/kafka-connect-lambda#11]
Currently, we log a message when the Connector starts up, and it includes all of the Connector configuration.

However, that configuration may contain secrets, such as Schema registry credentials.

The Connect framework already emits the configuration when the Connector starts up, and is smart enough to obfuscate properties marked as [ConfigDef.Type=PASSWORD](https://kafka.apache.org/10/javadoc/index.html?org/apache/kafka/common/config/ConfigDef.Type.html).

Please omit the configuration logging that we do here in the Connector `start` function.

**Comment by Chanjun-Liu** [comment]
fixed the problem by removing the properties of starting configuration logging for LambdaSinkTask and LambdaSinkConnector
