### ISSUE TITLE
Add Kafka message headers to payload

### ISSUE THREAD

**Issue by dylanmei** [Nordstrom/kafka-connect-lambda#21]
If headers are available on the Kafka message, they should be passed along as a map in the `headers` field of the invocation payload.

**Comment by SgtPepperLHCB** [comment]
SinkRecord.headers() are of type ConnectHeader which consist of key, value and schema.  Most typically, schema is Schema.STRING. Do we want to treat them as we do the SinkRecord key and value and serialize possible STRUCT, etc.?

**Comment by dylanmei** [comment]
I imagine we will treat it the exact same same way. _I assume we're talking about the JSON payload formatter._

However, looking at this, we may re-think our `payload.formatter.schema.visibility`  config. With "min" still being the default, we might break it up into:
- `payload.formatter.key.schema.visibility`
- `payload.formatter.value.schema.visibility`
- `payload.formatter.header.schema.visibility`

**Comment by dylanmei** [comment]
This work may be more appropriate for a Kafka Connect Transformation.
