### ISSUE TITLE
question: Are records within a topic and partition processed sequentially

### ISSUE THREAD

**Issue by devdoshi** [Nordstrom/kafka-connect-lambda#33]
This is a cool project! I am curious how it compares to https://docs.confluent.io/current/connect/kafka-connect-aws-lambda/index.html

My main question is: Are records within a given topic and partition processed sequentially? In the linked Confluent docs they make this explicit.

**Comment by dylanmei** [comment]
I recommend using Confluent's connector if you have a Confluent license. Otherwise, we can only use it for 30 days.

With this connector, records within a given topic and partition are processed sequentially.
