### ISSUE TITLE
Connector can assume IAM role

### ISSUE THREAD

**Issue by dylanmei** [Nordstrom/kafka-connect-lambda#4]
While a Lambda permissions policy can be created, in some cross-account situations it is more practical for the connector to assume a role that can invoke the Lambda. This is similar to [a feature we have on the SQS Connector](https://github.com/Nordstrom/kafka-connect-sqs#aws-assume-role-support-options).

If `aws.credentials.provider.class: com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider` is supplied, these options should  also be supported:
- `aws.credentials.provider.role.arn`: _required_ AWS IAM Role ARN providing the access
- `aws.credentials.provider.session.name:` _required_ STS Session name
- `aws.credentials.provider.external.id`: _optional_ External identifier used by the credential provider when assuming the role.

Otherwise, `com.amazonaws.auth.DefaultAWSCredentialsProviderChain` should be used, [documented here](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html).

**Comment by seananthonywilliams** [comment]
Added functionality; merged work branch into master; created release 1.0.0.
