### ISSUE TITLE
Specify version of release

### ISSUE THREAD

**Issue by dylanmei** [Nordstrom/kafka-connect-lambda#9]
The `v1.0.0` release [available here](https://github.com/Nordstrom/kafka-connect-lambda/releases/tag/v1.0.0) does not report the correct version when loaded as a Connect plugin. Instead, it reports as:

```
{
  "class": "com.nordstrom.kafka.connect.lambda.LambdaSinkConnector",
  "type": "sink",
  "version": "${project.version}"
}
```

Let's replace the release with one that contains the correct version.

**Comment by seananthonywilliams** [comment]
Enabled Maven templating plugin to properly interpolate project.version variable; merged work branch into master; created new release 1.0.1.
